### ISSUE TITLE
sigmas and kps_weights  parameters used in training and evaluation

### ISSUE THREAD

**Issue by yzrs** [chaneyddtt/ScarceNet#5]
Hi,Thanks for your contribution.
I'm also working on animal pose estimation and I'm curious about the **sigmas values for OKS computation** and **keypoints weights values for loss computation**. If we use the values provided by cocoAPI, the model won't perform well because those values work for human pose estimation with different keypoints definition.
So what are the values of the corresponding parameters you are using and where are they defined?
I would be grateful for your reply. Best wishes.

**Comment by chaneyddtt** [comment]
Hi @yzrs, thanks for your interests. I use the same weights for different key points for loss computation during training. As far as I know, most existing pose estimation approaches do not specify weights values for loss computation. For OKS computation, I use the values provided by cocoAPI since I did not find the values defined for animals. It would be more correct to use animal-specific values if available.

**Comment by yzrs** [comment]
I see. Thanks a lot for your reply!
